---
language: python

python:
  - "3.7"

services:
  - docker

env:
  matrix:
    - distribution="alpine:latest"
    - distribution="alpine:edge"
    - distribution="robertdebock/docker-centos-systemd:7"
    - distribution="robertdebock/docker-centos-systemd:latest"
    - distribution="robertdebock/docker-debian-systemd:latest"
    - distribution="robertdebock/docker-debian-systemd:stable"
    - distribution="robertdebock/docker-debian-systemd:unstable"
    - distribution="robertdebock/docker-fedora-systemd:latest"
    - distribution="robertdebock/docker-fedora-systemd:rawhide"
    - distribution="opensuse/leap"
    - distribution="robertdebock/docker-ubuntu-systemd:latest"
    - distribution="robertdebock/docker-ubuntu-systemd:devel"
    - distribution="robertdebock/docker-ubuntu-systemd:rolling"

matrix:
  allow_failures:
    - env: distribution="alpine:edge"
    - env: distribution="robertdebock/docker-debian-systemd:unstable"
    - env: distribution="robertdebock/docker-fedora-systemd:rawhide"
    - env: distribution="robertdebock/docker-ubuntu-systemd:devel"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install molecule
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "jxHXYkdZVYuPxxN51vhR2dMB9hN4jeRFpp5mSc8L8xO3A+7Mpa2VY67FfR4KXxQqg/HPNqeMamWcy6hMtnBMJfJ8darv8ygzGZXokjKH0AdmnK+A0kgSQiXvUYw0baV9e9uMFqcfqYLhROzi+8lcSIxj3YPVRXeQa3SHzIxXnlGVSb0gn2pFlECi/VO7PrVSXp3roGbvDbkW/RpvsBHf/WbQxsVNT3kFnEZ6uHNEjjWKZnl4q4lz3bwijmEJ+nKVmDj0IZZjOs18v42i9j1eOtcDH7UtsdWZAsly5SwU/OnlFLecbtfajLvM6ncv02UCEN8ahHIX5E2mkmAtShDUJopTxwSSfpcGqe2Zb1MT6PCb9BsIHtdicVmcCe7pb5AVelkwxIda5QWYE/MWNwlNSbbiLZmmD9DsZyDh30/WIVSdmyF84k/mvtGnQ7m5lSoJiRAoMHjUvi4xgPE8puo8v6HBbkVqVjW9GZHyQOGI2xRQgPTz5OjVwyqdqzokD7ozyRq5ErPiwTu8tfnWlip21TEFq7d1m9ctknM11fgj2E/WxdjO2NcZ00CiMG55KNrY3Te92phGvZEkBHF94HpEx9kK5NVVU04RYZ93LpmfQ2V86P/ukMvkQmW0CSv3VaSQCEmEtMT8PFs2TMkY02MqgYctEPTHS+v16M4giPCNrzw="
  email: false
