---

- name: assert | Test rsyslog_receiver
  ansible.builtin.assert:
    that:
      - rsyslog_receiver is defined
      - rsyslog_receiver is boolean
    quiet: true

- name: assert | Test rsyslog_preservefqdn
  ansible.builtin.assert:
    that:
      - rsyslog_preservefqdn is defined
      - rsyslog_preservefqdn is boolean
    quiet: true

- name: assert | Test rsyslog_remotes
  ansible.builtin.assert:
    that:
      - rsyslog_remotes is defined
      - rsyslog_remotes is iterable
    quiet: true

- name: assert | Test item in rsyslog_remotes
  ansible.builtin.assert:
    that:
      - item is mapping
      - "'selector' in item"
      - item.selector is string
      - item.selector is not none
      - "'hostname' in item"
      - item.hostname is string
      - item.hostname is not none
      - "'port' not in item or (item.port is number and item.port > 0 and item.port < 65536)"
      - "'tcp' not in item or item.tcp is boolean"
      - "'extra_params' not in item or item.extra_params is string"
    quiet: true
  loop: "{{ rsyslog_remotes }}"
  when:
    - rsyslog_remotes | length > 0

- name: assert | Test rsyslog_remote_template
  ansible.builtin.assert:
    that:
      - rsyslog_remote_template is defined
      - rsyslog_remote_template is string
    quiet: true

- name: assert | Test rsyslog_remote_extra_params
  ansible.builtin.assert:
    that:
      - rsyslog_remote_extra_params is defined
      - rsyslog_remote_extra_params is string
    quiet: true

- name: assert | Test rsyslog_dircreatemode
  ansible.builtin.assert:
    that:
      - rsyslog_dircreatemode is defined
      - rsyslog_dircreatemode is string
      - rsyslog_dircreatemode is not none
    quiet: true

- name: assert | Test rsyslog_filecreatemode
  ansible.builtin.assert:
    that:
      - rsyslog_filecreatemode is defined
      - rsyslog_filecreatemode is string
      - rsyslog_filecreatemode is not none
    quiet: true

- name: assert | Test rsyslog_config_owner
  ansible.builtin.assert:
    that:
      - rsyslog_config_owner is defined
      - rsyslog_config_owner is string
      - rsyslog_config_owner is not none
    quiet: true

- name: assert | Test rsyslog_config_group
  ansible.builtin.assert:
    that:
      - rsyslog_config_group is defined
      - rsyslog_config_group is string
      - rsyslog_config_group is not none
    quiet: true

- name: assert | Test rsyslog_config_mode
  ansible.builtin.assert:
    that:
      - rsyslog_config_mode is defined
      - rsyslog_config_mode is string
      - rsyslog_config_mode is not none
    quiet: true

- name: assert | Test rsyslog_config_dir_mode
  ansible.builtin.assert:
    that:
      - rsyslog_config_dir_mode is defined
      - rsyslog_config_dir_mode is string
      - rsyslog_config_dir_mode is not none
    quiet: true

- name: assert | Test rsyslog_mods
  ansible.builtin.assert:
    that:
      - rsyslog_mods is defined
      - rsyslog_mods is iterable
    quiet: true

- name: assert | Test item in rsyslog_mods
  ansible.builtin.assert:
    that:
      - item is defined
      - item is string
      - item in [ "imuxsock", "imjournal", "imklog", "immark", "imfile" ]
    quiet: true
  loop: "{{ rsyslog_mods }}"
  when:
    - rsyslog_mods | length > 0

- name: assert | Test rsyslog_deploy_default_config
  ansible.builtin.assert:
    that:
      - rsyslog_deploy_default_config is defined
      - rsyslog_deploy_default_config is boolean
    quiet: true

- name: assert | Test rsyslog_forward_rule_name
  ansible.builtin.assert:
    that:
      - rsyslog_forward_rule_name is defined
      - rsyslog_forward_rule_name is string
      - rsyslog_forward_rule_name is not none
    quiet: true
  when:
    - not rsyslog_deploy_default_config

- name: assert | Test rsyslog_config_file_format
  ansible.builtin.assert:
    that:
      - rsyslog_config_file_format is defined
      - rsyslog_config_file_format is string
      - rsyslog_config_file_format in [ "legacy", "advanced" ]
    quiet: true

- name: assert | Test rsyslog_package_state
  ansible.builtin.assert:
    that:
      - rsyslog_package_state is defined
      - rsyslog_package_state is string
      - rsyslog_package_state in [ "present", "latest" ]
    quiet: true

- name: assert | Test rsyslog_features
  ansible.builtin.assert:
    that:
      - rsyslog_features is iterable
    quiet: true
  when:
    - rsyslog_features is defined

- name: assert | Test rsyslog_omit_local_logging
  ansible.builtin.assert:
    that:
      - rsyslog_omit_local_logging is defined
      - rsyslog_omit_local_logging is boolean
    quiet: true

- name: assert | Test rsyslog_traditional_file_format
  ansible.builtin.assert:
    that:
      - rsyslog_traditional_file_format is defined
      - rsyslog_traditional_file_format is boolean
    quiet: true
